export interface Step {
  id: number;
  chapter: string;
  title: string;
  mission: string;
  hint: string;
  requiredKeyword: string;
  defaultFiles: {
    [key: string]: string;
  };
}

export const STEPS: Step[] = [
  // --- 第1章：HTML編 (STEP 1 ~ 10) ---
  { id: 1, chapter: "HTML編", title: "STEP 1: DOCTYPE宣言", mission: "<!DOCTYPE html> と入力してHTML5の宣言をしよう。", hint: "<!DOCTYPE html>", requiredKeyword: "<!DOCTYPE html>", defaultFiles: { "index.html": "", "style.css": "", "script.js": "" } },
  { id: 2, chapter: "HTML編", title: "STEP 2: htmlタグ", mission: "<html> と </html> を書いて土台を作ろう。", hint: "<html>\n\n</html>", requiredKeyword: "<html>", defaultFiles: { "index.html": "<!DOCTYPE html>\n", "style.css": "", "script.js": "" } },
  { id: 3, chapter: "HTML編", title: "STEP 3: headとbody", mission: "<head> と <body> タグを追加しよう。", hint: "<head></head>\n<body></body>", requiredKeyword: "body", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n  \n</html>", "style.css": "", "script.js": "" } },
  { id: 4, chapter: "HTML編", title: "STEP 4: ページタイトル", mission: "<title>マイサイト</title> を書こう。", hint: "<title>タイトル</title>", requiredKeyword: "<title>", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n  <head>\n    <title></title>\n  </head>\n  <body></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 5, chapter: "HTML編", title: "STEP 5: メイン見出し (h1)", mission: "<h1>見出し</h1> を書いてみよう。", hint: "<h1>私のサイト</h1>", requiredKeyword: "<h1>", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n  <head><title>Test</title></head>\n  <body>\n    \n  </body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 6, chapter: "HTML編", title: "STEP 6: サブ見出し (h2)", mission: "<h2>サブ見出し</h2> を追加しよう。", hint: "<h2>プロフィール</h2>", requiredKeyword: "<h2>", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n  <body>\n    <h1>Home</h1>\n    \n  </body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 7, chapter: "HTML編", title: "STEP 7: 段落 (p)", mission: "<p>文章</p> で段落を追加しよう。", hint: "<p>勉強中です</p>", requiredKeyword: "<p>", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n  <body>\n    <h1>Home</h1>\n    \n  </body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 8, chapter: "HTML編", title: "STEP 8: リスト (ul/li)", mission: "<ul> と <li> で箇条書きを作ろう。", hint: "<ul>\n  <li>項目</li>\n</ul>", requiredKeyword: "<li>", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n  <body>\n    <h2>好きなもの</h2>\n    \n  </body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 9, chapter: "HTML編", title: "STEP 9: リンク (a)", mission: `<a href="https://example.com">リンク</a> を作ろう。`, hint: '<a href="...">リンク</a>', requiredKeyword: "<a href", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n  <body>\n    \n  </body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 10, chapter: "HTML編", title: "STEP 10: HTML総仕上げ", mission: "ここまでのタグを組み合わせて骨組みを完成させよう。", hint: "<html>...</html>", requiredKeyword: "</html>", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><title>Portfolio</title></head>\n<body>\n  <h1>My Portfolio</h1>\n</body>\n</html>", "style.css": "", "script.js": "" } },

  // --- 第2章：CSS編 (STEP 11 ~ 20) ---
  { id: 11, chapter: "CSS編", title: "STEP 11: 文字色変更", mission: "style.cssに h1 { color: #4f46e5; } を書こう。", hint: "h1 {\n  color: #4f46e5;\n}", requiredKeyword: "color", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><h1>Hello</h1></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 12, chapter: "CSS編", title: "STEP 12: 背景と余白", mission: ".box に background-color と padding を設定しよう。", hint: ".box {\n  background: #f1f5f9;\n  padding: 20px;\n}", requiredKeyword: "padding", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><div class=\"box\">Card</div></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 13, chapter: "CSS編", title: "STEP 13: フォントサイズ", mission: "font-size を指定してみよう。", hint: "font-size: 18px;", requiredKeyword: "font-size", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><p class=\"text\">Text</p></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 14, chapter: "CSS編", title: "STEP 14: 角丸 (border-radius)", mission: "border-radius で角を丸くしよう。", hint: "border-radius: 12px;", requiredKeyword: "border-radius", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><div class=\"card\">Box</div></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 15, chapter: "CSS編", title: "STEP 15: 影 (box-shadow)", mission: "box-shadow で立体感をつけよう。", hint: "box-shadow: 0 10px 15px rgba(0,0,0,0.1);", requiredKeyword: "box-shadow", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><div class=\"shadow\">Shadow</div></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 16, chapter: "CSS編", title: "STEP 16: Flexbox横並び", mission: "display: flex; で要素を横並びにしよう。", hint: "display: flex;\ngap: 10px;", requiredKeyword: "display: flex", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><div class=\"container\"><div>1</div><div>2</div></div></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 17, chapter: "CSS編", title: "STEP 17: ホバーエフェクト", mission: ":hover を使ってマウスオーバー時の変化を作ろう。", hint: "btn:hover {\n  background: #4338ca;\n}", requiredKeyword: ":hover", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><button class=\"btn\">Button</button></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 18, chapter: "CSS編", title: "STEP 18: 中央寄せ", mission: "margin: 0 auto; で中央に配置しよう。", hint: "margin: 0 auto;", requiredKeyword: "margin", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><div class=\"wrapper\">Center</div></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 19, chapter: "CSS編", title: "STEP 19: 行間調整", mission: "line-height を設定して読みやすくしよう。", hint: "line-height: 1.8;", requiredKeyword: "line-height", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><p class=\"article\">Article text...</p></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 20, chapter: "CSS編", title: "STEP 20: CSS総仕上げ", mission: "プロフィールカードのデザインを完成させよう。", hint: "background, radius, shadowなどを組み合わせよう", requiredKeyword: "background", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><div class=\"profile-card\"><h2>Name</h2></div></body>\n</html>", "style.css": "", "script.js": "" } },

  // --- 第3章：JavaScript編 (STEP 21 ~ 30) ---
  { id: 21, chapter: "JavaScript編", title: "STEP 21: コンソール出力", mission: "script.jsに console.log('Hello!'); を書こう。", hint: "console.log('Hello!');", requiredKeyword: "console.log", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><script src=\"script.js\"></script></head>\n<body><h1>JS</h1></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 22, chapter: "JavaScript編", title: "STEP 22: 変数とアラート", mission: "alert() でポップアップを出そう。", hint: "let msg = 'こんにちは';\nalert(msg);", requiredKeyword: "alert", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 23, chapter: "JavaScript編", title: "STEP 23: 要素の取得", mission: "document.getElementById() で要素を取得しよう。", hint: "let el = document.getElementById('title');", requiredKeyword: "getElementById", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><h1 id=\"title\">Title</h1><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 24, chapter: "JavaScript編", title: "STEP 24: テキスト書き換え", mission: "innerText を使って文字を変更しよう。", hint: "document.getElementById('heading').innerText = '変更';", requiredKeyword: "innerText", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><h1 id=\"heading\">Old</h1><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 25, chapter: "JavaScript編", title: "STEP 25: クリックイベント", mission: "onclick を使ってクリックに反応させよう。", hint: "document.getElementById('myBtn').onclick = function() { ... }", requiredKeyword: "onclick", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><button id=\"myBtn\">Click</button><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 26, chapter: "JavaScript編", title: "STEP 26: イベント連動", mission: "ボタンを押して別要素の文字が変わる仕組みを作ろう。", hint: "onclick と innerText の組み合わせ", requiredKeyword: "onclick", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><h2 id=\"msg\">Text</h2><button id=\"btn\">Change</button><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 27, chapter: "JavaScript編", title: "STEP 27: スタイル変更", mission: "JSから .style.background を変更しよう。", hint: "box.style.background = '#3b82f6';", requiredKeyword: "style", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><div id=\"box\">Box</div><button id=\"btn\">Color</button><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 28, chapter: "JavaScript編", title: "STEP 28: カウンターアプリ", mission: "変数で数値を管理し、クリックで数字が増えるカウンターを作ろう。", hint: "let count = 0; count++;", requiredKeyword: "count", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><p id=\"counter\">0</p><button id=\"plusBtn\">+1</button><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 29, chapter: "JavaScript編", title: "STEP 29: 表示切替 (トグル)", mission: "if文を使って詳細の表示・非表示を切り替えよう。", hint: "if (isShow) { ... }", requiredKeyword: "if", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<body><button id=\"toggleBtn\">Toggle</button><p id=\"detail\">Detail</p><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } },
  { id: 30, chapter: "JavaScript編", title: "STEP 30: 総合完成アプリ", mission: "すべての技術を融合させてインタラクティブアプリを完成させよう！", hint: "HTML・CSS・JSを総動員しよう", requiredKeyword: "document", defaultFiles: { "index.html": "<!DOCTYPE html>\n<html>\n<head><link rel=\"stylesheet\" href=\"style.css\"></head>\n<body><div class=\"app\"><h1>App</h1></div><script src=\"script.js\"></script></body>\n</html>", "style.css": "", "script.js": "" } }
];